# Form implementation generated from reading ui file 'src/bitmessageqt/bitmessageui.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from typing import Optional


class Ui_MainWindow(object):
    def setupUi(self, MainWindow: QtWidgets.QMainWindow) -> None:
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(885, 580)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/newPrefix/images/can-icon-24px.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.inbox = QtWidgets.QWidget()
        self.inbox.setObjectName("inbox")
        self.gridLayout = QtWidgets.QGridLayout(self.inbox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.treeWidgetYourIdentities = QtWidgets.QTreeWidget(parent=self.inbox)

        self.treeWidgetYourIdentities.setObjectName("treeWidgetYourIdentities")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/newPrefix/images/identities.png"),
            QtGui.QIcon.Mode.Selected,
            QtGui.QIcon.State.Off,
        )
        header_item = self.treeWidgetYourIdentities.headerItem()
        if header_item is not None:
            header_item.setIcon(0, icon1)
        self.verticalLayout_12.addWidget(self.treeWidgetYourIdentities)
        self.pushButtonNewAddress = QtWidgets.QPushButton(parent=self.inbox)
        self.pushButtonNewAddress.setMaximumSize(QtCore.QSize(200, 16777215))

        self.pushButtonNewAddress.setObjectName("pushButtonNewAddress")
        self.verticalLayout_12.addWidget(self.pushButtonNewAddress, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        # Create sidebar container widget
        self.sidebarWidget = QtWidgets.QWidget()
        self.sidebarWidget.setLayout(self.verticalLayout_12)

        # Create splitter and add sidebar
        self.splitter = QtWidgets.QSplitter(QtCore.Qt.Orientation.Horizontal)
        self.splitter.addWidget(self.sidebarWidget)
        self.horizontalLayout_3.addWidget(self.splitter)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayoutSearch = QtWidgets.QHBoxLayout()
        self.horizontalLayoutSearch.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayoutSearch.setObjectName("horizontalLayoutSearch")
        self.inboxSearchLineEdit = QtWidgets.QLineEdit(parent=self.inbox)
        self.inboxSearchLineEdit.setObjectName("inboxSearchLineEdit")
        self.horizontalLayoutSearch.addWidget(self.inboxSearchLineEdit)
        self.inboxSearchOption = QtWidgets.QComboBox(parent=self.inbox)
        self.inboxSearchOption.setObjectName("inboxSearchOption")
        self.inboxSearchOption.addItem("")
        self.inboxSearchOption.addItem("")
        self.inboxSearchOption.addItem("")
        self.inboxSearchOption.addItem("")
        self.inboxSearchOption.addItem("")
        self.horizontalLayoutSearch.addWidget(self.inboxSearchOption)
        self.verticalLayout_7.addLayout(self.horizontalLayoutSearch)
        self.tableWidgetInbox = QtWidgets.QTableWidget()
        self.tableWidgetInbox.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.tableWidgetInbox.setAlternatingRowColors(True)
        self.tableWidgetInbox.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection
        )
        self.tableWidgetInbox.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows
        )
        self.tableWidgetInbox.setWordWrap(False)
        self.tableWidgetInbox.setObjectName("tableWidgetInbox")
        self.tableWidgetInbox.setColumnCount(4)
        self.tableWidgetInbox.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInbox.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInbox.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInbox.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInbox.setHorizontalHeaderItem(3, item)

        # Safe header configuration with None checks
        h_header: Optional[QtWidgets.QHeaderView] = (
            self.tableWidgetInbox.horizontalHeader()
        )
        if h_header is not None:
            h_header.setCascadingSectionResizes(True)
            h_header.setDefaultSectionSize(200)
            h_header.setHighlightSections(False)
            h_header.setMinimumSectionSize(27)
            h_header.setSortIndicatorShown(False)
            h_header.setStretchLastSection(True)

        v_header: Optional[QtWidgets.QHeaderView] = (
            self.tableWidgetInbox.verticalHeader()
        )
        if v_header is not None:
            v_header.setVisible(False)
            v_header.setDefaultSectionSize(26)
        # self.verticalLayout_7.addWidget(self.tableWidgetInbox)
        self.textEditInboxMessage = QtWidgets.QTextEdit()
        self.textEditInboxMessage.setMinimumSize(QtCore.QSize(0, 100))
        self.textEditInboxMessage.setBaseSize(QtCore.QSize(0, 500))
        self.textEditInboxMessage.setReadOnly(True)
        self.textEditInboxMessage.setObjectName("textEditInboxMessage")
        # self.verticalLayout_7.addWidget(self.textEditInboxMessage)

        # Create vertical splitter for message list and view
        self.splitter_2 = QtWidgets.QSplitter(QtCore.Qt.Orientation.Vertical)
        self.splitter_2.addWidget(self.tableWidgetInbox)
        self.splitter_2.addWidget(self.textEditInboxMessage)
        self.splitter_2.setCollapsible(0, False)
        self.splitter_2.setCollapsible(1, False)
        self.splitter_2.setSizes([300, 150])
        self.verticalLayout_7.addWidget(self.splitter_2)
        # Create right side container widget
        self.rightSideWidget = QtWidgets.QWidget()
        self.rightSideWidget.setLayout(self.verticalLayout_7)
        self.splitter.addWidget(self.rightSideWidget)

        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/newPrefix/images/inbox.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.tabWidget.addTab(self.inbox, icon2, "")
        self.send = QtWidgets.QWidget()
        self.send.setObjectName("send")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.send)
        self.gridLayout_7.setObjectName("gridLayout_7")
        # Send Tab Refactoring to use QSplitter
        # Create container for sidebar (AddressBook + Buttons)
        self.sendSidebar = QtWidgets.QWidget()
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sendSidebar)  # Added this line to define verticalLayout_2
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidgetAddressBook = QtWidgets.QTableWidget(parent=self.sendSidebar)
        self.tableWidgetAddressBook.setMaximumSize(QtCore.QSize(16777215, 16777215))  # Allow resizing
        self.tableWidgetAddressBook.setAlternatingRowColors(True)
        self.tableWidgetAddressBook.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection
        )
        self.tableWidgetAddressBook.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows
        )
        self.tableWidgetAddressBook.setObjectName("tableWidgetAddressBook")
        self.tableWidgetAddressBook.setColumnCount(2)
        self.tableWidgetAddressBook.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(":/newPrefix/images/addressbook.png"),
            QtGui.QIcon.Mode.Selected,
            QtGui.QIcon.State.Off,
        )
        item.setIcon(icon3)
        self.tableWidgetAddressBook.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAddressBook.setHorizontalHeaderItem(1, item)

        # Safe header configuration with None checks
        h_header = self.tableWidgetAddressBook.horizontalHeader()
        if h_header is not None:
            h_header.setCascadingSectionResizes(True)
            h_header.setDefaultSectionSize(200)
            h_header.setHighlightSections(False)
            h_header.setStretchLastSection(True)

        v_header = self.tableWidgetAddressBook.verticalHeader()
        if v_header is not None:
            v_header.setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidgetAddressBook)
        self.pushButtonAddAddressBook = QtWidgets.QPushButton(parent=self.sendSidebar)
        self.pushButtonAddAddressBook.setMaximumSize(QtCore.QSize(16777215, 16777215))  # Allow resizing
        self.pushButtonAddAddressBook.setObjectName("pushButtonAddAddressBook")
        self.verticalLayout_2.addWidget(self.pushButtonAddAddressBook)
        self.pushButtonFetchNamecoinID = QtWidgets.QPushButton(parent=self.sendSidebar)
        self.pushButtonFetchNamecoinID.setMaximumSize(QtCore.QSize(16777215, 16777215))  # Allow resizing
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButtonFetchNamecoinID.setFont(font)
        self.pushButtonFetchNamecoinID.setObjectName("pushButtonFetchNamecoinID")
        self.verticalLayout_2.addWidget(self.pushButtonFetchNamecoinID)
        # Create container for main content (Tabs + Send Button)
        self.sendContent = QtWidgets.QWidget()
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sendContent)  # Added this line to define verticalLayout
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidgetSend = QtWidgets.QTabWidget(parent=self.sendContent)
        self.tabWidgetSend.setObjectName("tabWidgetSend")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEditSubject = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEditSubject.setText("")
        self.lineEditSubject.setObjectName("lineEditSubject")
        self.gridLayout_2.addWidget(self.lineEditSubject, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.tab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.comboBoxSendFrom = QtWidgets.QComboBox(parent=self.tab)
        self.comboBoxSendFrom.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBoxSendFrom.setObjectName("comboBoxSendFrom")
        self.gridLayout_2.addWidget(self.comboBoxSendFrom, 0, 1, 1, 1)
        self.lineEditTo = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEditTo.setObjectName("lineEditTo")
        self.gridLayout_2.addWidget(self.lineEditTo, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.textEditMessage = QtWidgets.QTextEdit(parent=self.tab)
        self.textEditMessage.setObjectName("textEditMessage")
        self.verticalLayout_5.addWidget(self.textEditMessage)
        self.gridLayout_8.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tabWidgetSend.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_8 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEditSubjectBroadcast = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEditSubjectBroadcast.setText("")
        self.lineEditSubjectBroadcast.setObjectName("lineEditSubjectBroadcast")
        self.gridLayout_5.addWidget(self.lineEditSubjectBroadcast, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.comboBoxSendFromBroadcast = QtWidgets.QComboBox(parent=self.tab_2)
        self.comboBoxSendFromBroadcast.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBoxSendFromBroadcast.setObjectName("comboBoxSendFromBroadcast")
        self.gridLayout_5.addWidget(self.comboBoxSendFromBroadcast, 0, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_5)
        self.textEditMessageBroadcast = QtWidgets.QTextEdit(parent=self.tab_2)
        self.textEditMessageBroadcast.setObjectName("textEditMessageBroadcast")
        self.verticalLayout_6.addWidget(self.textEditMessageBroadcast)
        self.gridLayout_9.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidgetSend.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidgetSend)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButtonTTL = QtWidgets.QPushButton(parent=self.sendContent)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pushButtonTTL.sizePolicy().hasHeightForWidth()
        )
        self.pushButtonTTL.setSizePolicy(sizePolicy)
        self.pushButtonTTL.setMaximumSize(QtCore.QSize(32, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.ButtonText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.ButtonText,
            brush,
        )
        self.pushButtonTTL.setPalette(palette)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.pushButtonTTL.setFont(font)
        self.pushButtonTTL.setFlat(True)
        self.pushButtonTTL.setObjectName("pushButtonTTL")
        self.horizontalLayout_5.addWidget(self.pushButtonTTL)
        self.horizontalSliderTTL = QtWidgets.QSlider(parent=self.sendContent)
        self.horizontalSliderTTL.setMinimumSize(QtCore.QSize(35, 0))
        self.horizontalSliderTTL.setMaximumSize(QtCore.QSize(70, 16777215))
        self.horizontalSliderTTL.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSliderTTL.setInvertedAppearance(False)
        self.horizontalSliderTTL.setInvertedControls(False)
        self.horizontalSliderTTL.setObjectName("horizontalSliderTTL")
        self.horizontalLayout_5.addWidget(self.horizontalSliderTTL)
        self.labelHumanFriendlyTTLDescription = QtWidgets.QLabel(parent=self.sendContent)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelHumanFriendlyTTLDescription.sizePolicy().hasHeightForWidth()
        )
        self.labelHumanFriendlyTTLDescription.setSizePolicy(sizePolicy)
        self.labelHumanFriendlyTTLDescription.setMinimumSize(QtCore.QSize(200, 0))
        self.labelHumanFriendlyTTLDescription.setMaximumSize(QtCore.QSize(300, 16777215))
        self.labelHumanFriendlyTTLDescription.setObjectName(
            "labelHumanFriendlyTTLDescription"
        )
        self.horizontalLayout_5.addWidget(self.labelHumanFriendlyTTLDescription)
        self.pushButtonSend = QtWidgets.QPushButton(parent=self.sendContent)
        self.pushButtonSend.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.horizontalLayout_5.addWidget(self.pushButtonSend)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        
        # Create Splitter
        self.splitterSend = QtWidgets.QSplitter(QtCore.Qt.Orientation.Horizontal)
        self.splitterSend.addWidget(self.sendSidebar)
        self.splitterSend.addWidget(self.sendContent)
        self.splitterSend.setObjectName("splitterSend")

        # Add to grid layout
        self.gridLayout_7.addWidget(self.splitterSend, 0, 0, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap(":/newPrefix/images/send.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.tabWidget.addTab(self.send, icon4, "")
        self.subscriptions = QtWidgets.QWidget()
        self.subscriptions.setObjectName("subscriptions")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.subscriptions)
        self.gridLayout_3.setObjectName("gridLayout_3")
        # Subscriptions Tab Refactoring to use QSplitter
        
        # Create container for sidebar (TreeWidget + Button)
        self.subscriptionsSidebar = QtWidgets.QWidget()
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.subscriptionsSidebar)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        # ... TreeWidget setup
        self.treeWidgetSubscriptions = QtWidgets.QTreeWidget(parent=self.subscriptionsSidebar)
        self.treeWidgetSubscriptions.setMaximumSize(QtCore.QSize(16777215, 16777215))  # Allow resizing
        self.treeWidgetSubscriptions.setAlternatingRowColors(True)
        self.treeWidgetSubscriptions.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.SingleSelection
        )
        self.treeWidgetSubscriptions.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows
        )
        self.treeWidgetSubscriptions.setObjectName("treeWidgetSubscriptions")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap(":/newPrefix/images/subscriptions.png"),
            QtGui.QIcon.Mode.Selected,
            QtGui.QIcon.State.Off,
        )
        header_item = self.treeWidgetSubscriptions.headerItem()
        if header_item is not None:
            header_item.setIcon(0, icon5)
        self.verticalLayout_3.addWidget(self.treeWidgetSubscriptions)
        self.pushButtonAddSubscription = QtWidgets.QPushButton(
            parent=self.subscriptionsSidebar
        )
        self.pushButtonAddSubscription.setMaximumSize(QtCore.QSize(16777215, 16777215))  # Allow resizing
        self.pushButtonAddSubscription.setObjectName("pushButtonAddSubscription")
        self.verticalLayout_3.addWidget(self.pushButtonAddSubscription)

        # Create container for main content (Search + Table + Message View)
        self.subscriptionsContent = QtWidgets.QWidget()
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.subscriptionsContent)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.inboxSearchLineEditSubscriptions = QtWidgets.QLineEdit(
            parent=self.subscriptionsContent
        )
        self.inboxSearchLineEditSubscriptions.setObjectName(
            "inboxSearchLineEditSubscriptions"
        )
        self.horizontalLayout_2.addWidget(self.inboxSearchLineEditSubscriptions)
        self.inboxSearchOptionSubscriptions = QtWidgets.QComboBox(
            parent=self.subscriptionsContent
        )
        self.inboxSearchOptionSubscriptions.setObjectName(
            "inboxSearchOptionSubscriptions"
        )
        self.inboxSearchOptionSubscriptions.addItem("")
        self.inboxSearchOptionSubscriptions.addItem("")
        self.inboxSearchOptionSubscriptions.addItem("")
        self.inboxSearchOptionSubscriptions.addItem("")
        self.inboxSearchOptionSubscriptions.addItem("")
        self.horizontalLayout_2.addWidget(self.inboxSearchOptionSubscriptions)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)

        # Vertical Splitter for Message List and Message View
        self.splitterSubscriptionsVertical = QtWidgets.QSplitter(QtCore.Qt.Orientation.Vertical)
        self.splitterSubscriptionsVertical.setObjectName("splitterSubscriptionsVertical")

        self.tableWidgetInboxSubscriptions = QtWidgets.QTableWidget(
            parent=self.splitterSubscriptionsVertical
        )
        self.tableWidgetInboxSubscriptions.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.tableWidgetInboxSubscriptions.setAlternatingRowColors(True)
        self.tableWidgetInboxSubscriptions.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection
        )
        self.tableWidgetInboxSubscriptions.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows
        )
        self.tableWidgetInboxSubscriptions.setWordWrap(False)
        self.tableWidgetInboxSubscriptions.setObjectName(
            "tableWidgetInboxSubscriptions"
        )
        self.tableWidgetInboxSubscriptions.setColumnCount(4)
        self.tableWidgetInboxSubscriptions.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInboxSubscriptions.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInboxSubscriptions.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInboxSubscriptions.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInboxSubscriptions.setHorizontalHeaderItem(3, item)

        # Safe header configuration with None checks
        h_header = self.tableWidgetInboxSubscriptions.horizontalHeader()
        if h_header is not None:
            h_header.setCascadingSectionResizes(True)
            h_header.setDefaultSectionSize(200)
            h_header.setHighlightSections(False)
            h_header.setMinimumSectionSize(27)
            h_header.setSortIndicatorShown(False)
            h_header.setStretchLastSection(True)

        v_header = self.tableWidgetInboxSubscriptions.verticalHeader()
        if v_header is not None:
            v_header.setVisible(False)
            v_header.setDefaultSectionSize(26)

        self.textEditInboxMessageSubscriptions = QtWidgets.QTextEdit(
            parent=self.splitterSubscriptionsVertical
        )
        self.textEditInboxMessageSubscriptions.setBaseSize(QtCore.QSize(0, 500))
        self.textEditInboxMessageSubscriptions.setReadOnly(True)
        self.textEditInboxMessageSubscriptions.setObjectName(
            "textEditInboxMessageSubscriptions"
        )
        
        self.verticalLayout_4.addWidget(self.splitterSubscriptionsVertical)

        # Create Splitter
        self.splitterSubscriptions = QtWidgets.QSplitter(QtCore.Qt.Orientation.Horizontal)
        self.splitterSubscriptions.addWidget(self.subscriptionsSidebar)
        self.splitterSubscriptions.addWidget(self.subscriptionsContent)
        self.splitterSubscriptions.setObjectName("splitterSubscriptions")
        
        # Add splitter to grid layout
        self.gridLayout_3.addWidget(self.splitterSubscriptions, 0, 0, 1, 1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap(":/newPrefix/images/subscriptions.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.tabWidget.addTab(self.subscriptions, icon6, "")
        self.chans = QtWidgets.QWidget()
        self.chans.setObjectName("chans")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.chans)
        self.gridLayout_4.setObjectName("gridLayout_4")
        # Chans Tab Refactoring to use QSplitter

        # Create container for sidebar
        self.chansSidebar = QtWidgets.QWidget()
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.chansSidebar)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.treeWidgetChans = QtWidgets.QTreeWidget(parent=self.chansSidebar)
        self.treeWidgetChans.setMaximumSize(QtCore.QSize(16777215, 16777215))  # Allow resizing
        self.treeWidgetChans.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.treeWidgetChans.setLineWidth(1)
        self.treeWidgetChans.setAlternatingRowColors(True)
        self.treeWidgetChans.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.SingleSelection
        )
        self.treeWidgetChans.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows
        )
        self.treeWidgetChans.setObjectName("treeWidgetChans")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(
            QtGui.QPixmap(":/newPrefix/images/can-icon-16px.png"),
            QtGui.QIcon.Mode.Selected,
            QtGui.QIcon.State.Off,
        )
        header_item = self.treeWidgetChans.headerItem()
        if header_item is not None:
            header_item.setIcon(0, icon7)
        self.verticalLayout_17.addWidget(self.treeWidgetChans)
        self.pushButtonAddChan = QtWidgets.QPushButton(parent=self.chansSidebar)
        self.pushButtonAddChan.setMaximumSize(QtCore.QSize(16777215, 16777215))  # Allow resizing
        self.pushButtonAddChan.setObjectName("pushButtonAddChan")
        self.verticalLayout_17.addWidget(self.pushButtonAddChan)
        
        # Create container for main content
        self.chansContent = QtWidgets.QWidget()
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.chansContent)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.inboxSearchLineEditChans = QtWidgets.QLineEdit(parent=self.chansContent)
        self.inboxSearchLineEditChans.setObjectName("inboxSearchLineEditChans")
        self.horizontalLayout_6.addWidget(self.inboxSearchLineEditChans)
        self.inboxSearchOptionChans = QtWidgets.QComboBox(parent=self.chansContent)
        self.inboxSearchOptionChans.setObjectName("inboxSearchOptionChans")
        self.inboxSearchOptionChans.addItem("")
        self.inboxSearchOptionChans.addItem("")
        self.inboxSearchOptionChans.addItem("")
        self.inboxSearchOptionChans.addItem("")
        self.inboxSearchOptionChans.addItem("")
        self.horizontalLayout_6.addWidget(self.inboxSearchOptionChans)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)

        # Vertical Splitter for Message List and Message View
        self.splitterChansVertical = QtWidgets.QSplitter(QtCore.Qt.Orientation.Vertical)
        self.splitterChansVertical.setObjectName("splitterChansVertical")

        self.tableWidgetInboxChans = QtWidgets.QTableWidget(parent=self.splitterChansVertical)
        self.tableWidgetInboxChans.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.tableWidgetInboxChans.setAlternatingRowColors(True)
        self.tableWidgetInboxChans.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection
        )
        self.tableWidgetInboxChans.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows
        )
        self.tableWidgetInboxChans.setWordWrap(False)
        self.tableWidgetInboxChans.setObjectName("tableWidgetInboxChans")
        self.tableWidgetInboxChans.setColumnCount(4)
        self.tableWidgetInboxChans.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInboxChans.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInboxChans.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInboxChans.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInboxChans.setHorizontalHeaderItem(3, item)
        # Safe header configuration with None checks
        h_header = self.tableWidgetInboxChans.horizontalHeader()
        if h_header is not None:
            h_header.setCascadingSectionResizes(True)
            h_header.setDefaultSectionSize(200)
            h_header.setHighlightSections(False)
            h_header.setMinimumSectionSize(27)
            h_header.setSortIndicatorShown(False)
            h_header.setStretchLastSection(True)

        v_header = self.tableWidgetInboxChans.verticalHeader()
        if v_header is not None:
            v_header.setVisible(False)
            v_header.setDefaultSectionSize(26)
        self.textEditInboxMessageChans = QtWidgets.QTextEdit(parent=self.splitterChansVertical)
        self.textEditInboxMessageChans.setBaseSize(QtCore.QSize(0, 500))
        self.textEditInboxMessageChans.setReadOnly(True)
        self.textEditInboxMessageChans.setObjectName("textEditInboxMessageChans")

        self.verticalLayout_8.addWidget(self.splitterChansVertical)
        # Create Splitter
        self.splitterChans = QtWidgets.QSplitter(QtCore.Qt.Orientation.Horizontal)
        self.splitterChans.addWidget(self.chansSidebar)
        self.splitterChans.addWidget(self.chansContent)
        self.splitterChans.setObjectName("splitterChans")
        # Add to grid layout
        self.gridLayout_4.addWidget(self.splitterChans, 0, 0, 1, 1)
        
        icon8 = QtGui.QIcon()
        icon8.addPixmap(
            QtGui.QPixmap(":/newPrefix/images/can-icon-16px.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.tabWidget.addTab(self.chans, icon8, "")
        self.blackwhitelist = QtWidgets.QWidget()
        self.blackwhitelist.setObjectName("blackwhitelist")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.blackwhitelist)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.radioButtonBlacklist = QtWidgets.QRadioButton(parent=self.blackwhitelist)
        self.radioButtonBlacklist.setChecked(True)
        self.radioButtonBlacklist.setObjectName("radioButtonBlacklist")
        self.gridLayout_6.addWidget(self.radioButtonBlacklist, 0, 0, 1, 2)
        self.radioButtonWhitelist = QtWidgets.QRadioButton(parent=self.blackwhitelist)
        self.radioButtonWhitelist.setObjectName("radioButtonWhitelist")
        self.gridLayout_6.addWidget(self.radioButtonWhitelist, 1, 0, 1, 2)
        self.pushButtonAddBlacklist = QtWidgets.QPushButton(parent=self.blackwhitelist)
        self.pushButtonAddBlacklist.setObjectName("pushButtonAddBlacklist")
        self.gridLayout_6.addWidget(self.pushButtonAddBlacklist, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            689,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_6.addItem(spacerItem, 2, 1, 1, 1)
        self.tableWidgetBlacklist = QtWidgets.QTableWidget(parent=self.blackwhitelist)
        self.tableWidgetBlacklist.setAlternatingRowColors(True)
        self.tableWidgetBlacklist.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.SingleSelection
        )
        self.tableWidgetBlacklist.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows
        )
        self.tableWidgetBlacklist.setObjectName("tableWidgetBlacklist")
        self.tableWidgetBlacklist.setColumnCount(2)
        self.tableWidgetBlacklist.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBlacklist.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBlacklist.setHorizontalHeaderItem(1, item)

        # Safe header configuration with None checks
        h_header = self.tableWidgetBlacklist.horizontalHeader()
        if h_header is not None:
            h_header.setCascadingSectionResizes(True)
            h_header.setDefaultSectionSize(400)
            h_header.setHighlightSections(False)
            h_header.setSortIndicatorShown(False)
            h_header.setStretchLastSection(True)

        v_header = self.tableWidgetBlacklist.verticalHeader()
        if v_header is not None:
            v_header.setVisible(False)
        self.gridLayout_6.addWidget(self.tableWidgetBlacklist, 3, 0, 1, 2)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(
            QtGui.QPixmap(":/newPrefix/images/blacklist.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.tabWidget.addTab(self.blackwhitelist, icon9, "")
        self.networkstatus = QtWidgets.QWidget()
        self.networkstatus.setObjectName("networkstatus")
        self.pushButtonStatusIcon = QtWidgets.QPushButton(parent=self.networkstatus)
        self.pushButtonStatusIcon.setGeometry(QtCore.QRect(680, 440, 21, 23))
        self.pushButtonStatusIcon.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(
            QtGui.QPixmap(":/newPrefix/images/redicon.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButtonStatusIcon.setIcon(icon10)
        self.pushButtonStatusIcon.setFlat(True)
        self.pushButtonStatusIcon.setObjectName("pushButtonStatusIcon")
        self.tableWidgetConnectionCount = QtWidgets.QTableWidget(
            parent=self.networkstatus
        )
        self.tableWidgetConnectionCount.setGeometry(QtCore.QRect(20, 70, 241, 241))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush
        )
        self.tableWidgetConnectionCount.setPalette(palette)
        self.tableWidgetConnectionCount.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.tableWidgetConnectionCount.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.tableWidgetConnectionCount.setProperty("showDropIndicator", False)
        self.tableWidgetConnectionCount.setAlternatingRowColors(True)
        self.tableWidgetConnectionCount.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.NoSelection
        )
        self.tableWidgetConnectionCount.setObjectName("tableWidgetConnectionCount")
        self.tableWidgetConnectionCount.setColumnCount(2)
        self.tableWidgetConnectionCount.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetConnectionCount.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetConnectionCount.setHorizontalHeaderItem(1, item)

        # Safe header configuration with None checks
        h_header = self.tableWidgetConnectionCount.horizontalHeader()
        if h_header is not None:
            h_header.setCascadingSectionResizes(True)
            h_header.setHighlightSections(False)
            h_header.setStretchLastSection(True)

        v_header = self.tableWidgetConnectionCount.verticalHeader()
        if v_header is not None:
            v_header.setVisible(False)
        self.labelTotalConnections = QtWidgets.QLabel(parent=self.networkstatus)
        self.labelTotalConnections.setGeometry(QtCore.QRect(20, 30, 401, 16))
        self.labelTotalConnections.setObjectName("labelTotalConnections")
        self.labelStartupTime = QtWidgets.QLabel(parent=self.networkstatus)
        self.labelStartupTime.setGeometry(QtCore.QRect(320, 110, 331, 20))
        self.labelStartupTime.setObjectName("labelStartupTime")
        self.labelMessageCount = QtWidgets.QLabel(parent=self.networkstatus)
        self.labelMessageCount.setGeometry(QtCore.QRect(350, 130, 361, 16))
        self.labelMessageCount.setObjectName("labelMessageCount")
        self.labelPubkeyCount = QtWidgets.QLabel(parent=self.networkstatus)
        self.labelPubkeyCount.setGeometry(QtCore.QRect(350, 170, 331, 16))
        self.labelPubkeyCount.setObjectName("labelPubkeyCount")
        self.labelBroadcastCount = QtWidgets.QLabel(parent=self.networkstatus)
        self.labelBroadcastCount.setGeometry(QtCore.QRect(350, 150, 351, 16))
        self.labelBroadcastCount.setObjectName("labelBroadcastCount")
        self.labelLookupsPerSecond = QtWidgets.QLabel(parent=self.networkstatus)
        self.labelLookupsPerSecond.setGeometry(QtCore.QRect(320, 250, 291, 16))
        self.labelLookupsPerSecond.setObjectName("labelLookupsPerSecond")
        self.labelBytesRecvCount = QtWidgets.QLabel(parent=self.networkstatus)
        self.labelBytesRecvCount.setGeometry(QtCore.QRect(350, 210, 251, 16))
        self.labelBytesRecvCount.setObjectName("labelBytesRecvCount")
        self.labelBytesSentCount = QtWidgets.QLabel(parent=self.networkstatus)
        self.labelBytesSentCount.setGeometry(QtCore.QRect(350, 230, 251, 16))
        self.labelBytesSentCount.setObjectName("labelBytesSentCount")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(
            QtGui.QPixmap(":/newPrefix/images/networkstatus.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.tabWidget.addTab(self.networkstatus, icon11, "")
        self.gridLayout_10.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 885, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(parent=self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setMaximumSize(QtCore.QSize(16777215, 22))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_keys = QtGui.QAction(parent=MainWindow)
        self.actionImport_keys.setObjectName("actionImport_keys")
        self.actionManageKeys = QtGui.QAction(parent=MainWindow)
        self.actionManageKeys.setCheckable(False)
        self.actionManageKeys.setEnabled(True)
        icon = QtGui.QIcon.fromTheme("dialog-password")
        self.actionManageKeys.setIcon(icon)
        self.actionManageKeys.setObjectName("actionManageKeys")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("application-exit")
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("help-contents")
        self.actionHelp.setIcon(icon)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("help-about")
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSettings = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("document-properties")
        self.actionSettings.setIcon(icon)
        self.actionSettings.setObjectName("actionSettings")
        self.actionRegenerateDeterministicAddresses = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("view-refresh")
        self.actionRegenerateDeterministicAddresses.setIcon(icon)
        self.actionRegenerateDeterministicAddresses.setObjectName(
            "actionRegenerateDeterministicAddresses"
        )
        self.actionDeleteAllTrashedMessages = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("user-trash")
        self.actionDeleteAllTrashedMessages.setIcon(icon)
        self.actionDeleteAllTrashedMessages.setObjectName(
            "actionDeleteAllTrashedMessages"
        )
        self.actionJoinChan = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("contact-new")
        self.actionJoinChan.setIcon(icon)
        self.actionJoinChan.setObjectName("actionJoinChan")
        self.actionNetworkSwitch = QtGui.QAction(parent=MainWindow)
        self.actionNetworkSwitch.setObjectName("actionNetworkSwitch")
        self.actionSupport = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("help-support")
        self.actionSupport.setIcon(icon)
        self.actionSupport.setObjectName("actionSupport")
        self.menuFile.addAction(self.actionManageKeys)
        self.menuFile.addAction(self.actionNetworkSwitch)
        self.menuFile.addAction(self.actionDeleteAllTrashedMessages)
        self.menuFile.addAction(self.actionRegenerateDeterministicAddresses)
        self.menuFile.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionSupport)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidgetSend.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # Tab order within Inbox tab
        MainWindow.setTabOrder(self.tableWidgetInbox, self.textEditInboxMessage)

        # Tab order within Send tab
        MainWindow.setTabOrder(self.comboBoxSendFrom, self.lineEditTo)
        MainWindow.setTabOrder(self.lineEditTo, self.lineEditSubject)
        MainWindow.setTabOrder(self.lineEditSubject, self.textEditMessage)
        MainWindow.setTabOrder(self.textEditMessage, self.pushButtonSend)

        # Tab order within Subscriptions tab (if any specific order needed)

        # Tab order within Blacklist tab
        MainWindow.setTabOrder(self.radioButtonBlacklist, self.radioButtonWhitelist)
        MainWindow.setTabOrder(self.radioButtonWhitelist, self.pushButtonAddBlacklist)
        MainWindow.setTabOrder(self.pushButtonAddBlacklist, self.tableWidgetBlacklist)

        # Tab order within Network Status tab
        MainWindow.setTabOrder(
            self.tableWidgetConnectionCount, self.pushButtonStatusIcon
        )

    def retranslateUi(self, MainWindow: QtWidgets.QMainWindow) -> None:
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bitmessage"))
        header_item: Optional[QtWidgets.QTreeWidgetItem] = (
            self.treeWidgetYourIdentities.headerItem()
        )
        if header_item is not None:
            header_item.setText(0, _translate("MainWindow", "Identities"))
        self.pushButtonNewAddress.setText(_translate("MainWindow", "New Indentitiy"))
        self.inboxSearchLineEdit.setPlaceholderText(_translate("MainWindow", "Search"))
        self.inboxSearchOption.setItemText(0, _translate("MainWindow", "All"))
        self.inboxSearchOption.setItemText(1, _translate("MainWindow", "To"))
        self.inboxSearchOption.setItemText(2, _translate("MainWindow", "From"))
        self.inboxSearchOption.setItemText(3, _translate("MainWindow", "Subject"))
        self.inboxSearchOption.setItemText(4, _translate("MainWindow", "Message"))
        self.tableWidgetInbox.setSortingEnabled(True)
        item: Optional[QtWidgets.QTableWidgetItem] = (
            self.tableWidgetInbox.horizontalHeaderItem(0)
        )
        if item is not None:
            item.setText(_translate("MainWindow", "To"))
        item = self.tableWidgetInbox.horizontalHeaderItem(1)
        if item is not None:
            item.setText(_translate("MainWindow", "From"))
        item = self.tableWidgetInbox.horizontalHeaderItem(2)
        if item is not None:
            item.setText(_translate("MainWindow", "Subject"))
        item = self.tableWidgetInbox.horizontalHeaderItem(3)
        if item is not None:
            item.setText(_translate("MainWindow", "Received"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.inbox), _translate("MainWindow", "Messages")
        )
        self.tableWidgetAddressBook.setSortingEnabled(True)
        item = self.tableWidgetAddressBook.horizontalHeaderItem(0)
        if item is not None:
            item.setText(_translate("MainWindow", "Address book"))
        item = self.tableWidgetAddressBook.horizontalHeaderItem(1)
        if item is not None:
            item.setText(_translate("MainWindow", "Address"))
        self.pushButtonAddAddressBook.setText(_translate("MainWindow", "Add Contact"))
        self.pushButtonFetchNamecoinID.setText(
            _translate("MainWindow", "Fetch Namecoin ID")
        )
        self.label_3.setText(_translate("MainWindow", "Subject:"))
        self.label_2.setText(_translate("MainWindow", "From:"))
        self.label.setText(_translate("MainWindow", "To:"))
        self.textEditMessage.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-size:9pt; font-weight:400; font-style:normal;\">\n"
                "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                "-qt-block-indent:0; text-indent:0px; "
                "\"><br /></p></body></html>",
            )
        )
        self.tabWidgetSend.setTabText(
            self.tabWidgetSend.indexOf(self.tab),
            _translate("MainWindow", "Send ordinary Message"),
        )
        self.label_8.setText(_translate("MainWindow", "From:"))
        self.label_7.setText(_translate("MainWindow", "Subject:"))
        self.textEditMessageBroadcast.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-size:9pt; font-weight:400; font-style:normal;\">\n"
                "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                "-qt-block-indent:0; text-indent:0px; "
                "\"><br /></p></body></html>",
            )
        )
        self.tabWidgetSend.setTabText(
            self.tabWidgetSend.indexOf(self.tab_2),
            _translate("MainWindow", "Send Message to your Subscribers"),
        )
        self.pushButtonTTL.setText(_translate("MainWindow", "TTL:"))
        self.labelHumanFriendlyTTLDescription.setText(
            _translate("MainWindow", "X days")
        )
        self.pushButtonSend.setText(_translate("MainWindow", "Send"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.send), _translate("MainWindow", "Send")
        )
        header_item = self.treeWidgetSubscriptions.headerItem()
        if header_item is not None:
            header_item.setText(0, _translate("MainWindow", "Subscriptions"))
        self.pushButtonAddSubscription.setText(
            _translate("MainWindow", "Add new Subscription")
        )
        self.inboxSearchLineEditSubscriptions.setPlaceholderText(
            _translate("MainWindow", "Search")
        )
        self.inboxSearchOptionSubscriptions.setItemText(
            0, _translate("MainWindow", "All")
        )
        self.inboxSearchOptionSubscriptions.setItemText(
            1, _translate("MainWindow", "To")
        )
        self.inboxSearchOptionSubscriptions.setItemText(
            2, _translate("MainWindow", "From")
        )
        self.inboxSearchOptionSubscriptions.setItemText(
            3, _translate("MainWindow", "Subject")
        )
        self.inboxSearchOptionSubscriptions.setItemText(
            4, _translate("MainWindow", "Message")
        )
        self.tableWidgetInboxSubscriptions.setSortingEnabled(True)
        item = self.tableWidgetInboxSubscriptions.horizontalHeaderItem(0)
        if item is not None:
            item.setText(_translate("MainWindow", "To"))
        item = self.tableWidgetInboxSubscriptions.horizontalHeaderItem(1)
        if item is not None:
            item.setText(_translate("MainWindow", "From"))
        item = self.tableWidgetInboxSubscriptions.horizontalHeaderItem(2)
        if item is not None:
            item.setText(_translate("MainWindow", "Subject"))
        item = self.tableWidgetInboxSubscriptions.horizontalHeaderItem(3)
        if item is not None:
            item.setText(_translate("MainWindow", "Received"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.subscriptions),
            _translate("MainWindow", "Subscriptions"),
        )
        header_item = self.treeWidgetChans.headerItem()
        if header_item is not None:
            header_item.setText(0, _translate("MainWindow", "Chans"))
        self.pushButtonAddChan.setText(_translate("MainWindow", "Add Chan"))
        self.inboxSearchLineEditChans.setPlaceholderText(
            _translate("MainWindow", "Search")
        )
        self.inboxSearchOptionChans.setItemText(0, _translate("MainWindow", "All"))
        self.inboxSearchOptionChans.setItemText(1, _translate("MainWindow", "To"))
        self.inboxSearchOptionChans.setItemText(2, _translate("MainWindow", "From"))
        self.inboxSearchOptionChans.setItemText(3, _translate("MainWindow", "Subject"))
        self.inboxSearchOptionChans.setItemText(4, _translate("MainWindow", "Message"))
        self.tableWidgetInboxChans.setSortingEnabled(True)
        item = self.tableWidgetInboxChans.horizontalHeaderItem(0)
        if item is not None:
            item.setText(_translate("MainWindow", "To"))
        item = self.tableWidgetInboxChans.horizontalHeaderItem(1)
        if item is not None:
            item.setText(_translate("MainWindow", "From"))
        item = self.tableWidgetInboxChans.horizontalHeaderItem(2)
        if item is not None:
            item.setText(_translate("MainWindow", "Subject"))
        item = self.tableWidgetInboxChans.horizontalHeaderItem(3)
        if item is not None:
            item.setText(_translate("MainWindow", "Received"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.chans), _translate("MainWindow", "Chans")
        )
        self.radioButtonBlacklist.setText(
            _translate(
                "MainWindow",
                "Use a Blacklist (Allow all incoming messages except those on the Blacklist)",
            )
        )
        self.radioButtonWhitelist.setText(
            _translate(
                "MainWindow",
                "Use a Whitelist (Block all incoming messages except those on the Whitelist)",
            )
        )
        self.pushButtonAddBlacklist.setText(_translate("MainWindow", "Add new entry"))
        self.tableWidgetBlacklist.setSortingEnabled(True)
        item = self.tableWidgetBlacklist.horizontalHeaderItem(0)
        if item is not None:
            item.setText(_translate("MainWindow", "Name or Label"))
        item = self.tableWidgetBlacklist.horizontalHeaderItem(1)
        if item is not None:
            item.setText(_translate("MainWindow", "Address"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.blackwhitelist),
            _translate("MainWindow", "Blacklist"),
        )
        item = self.tableWidgetConnectionCount.horizontalHeaderItem(0)
        if item is not None:
            item.setText(_translate("MainWindow", "Stream #"))
        item = self.tableWidgetConnectionCount.horizontalHeaderItem(1)
        if item is not None:
            item.setText(_translate("MainWindow", "Connections"))
        self.labelTotalConnections.setText(
            _translate("MainWindow", "Total connections:")
        )
        self.labelStartupTime.setText(_translate("MainWindow", "Since startup:"))
        self.labelMessageCount.setText(
            _translate("MainWindow", "Processed 0 person-to-person messages.")
        )
        self.labelPubkeyCount.setText(
            _translate("MainWindow", "Processed 0 public keys.")
        )
        self.labelBroadcastCount.setText(
            _translate("MainWindow", "Processed 0 broadcasts.")
        )
        self.labelLookupsPerSecond.setText(
            _translate("MainWindow", "Inventory lookups per second: 0")
        )
        self.labelBytesRecvCount.setText(_translate("MainWindow", "Down: 0 KB/s"))
        self.labelBytesSentCount.setText(_translate("MainWindow", "Up: 0 KB/s"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.networkstatus),
            _translate("MainWindow", "Network Status"),
        )
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionImport_keys.setText(_translate("MainWindow", "Import keys"))
        self.actionManageKeys.setText(_translate("MainWindow", "Manage keys"))
        self.actionExit.setText(_translate("MainWindow", "Quit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setShortcut(_translate("MainWindow", "F1"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionRegenerateDeterministicAddresses.setText(
            _translate("MainWindow", "Regenerate deterministic addresses")
        )
        self.actionDeleteAllTrashedMessages.setText(
            _translate("MainWindow", "Delete all trashed messages")
        )
        self.actionJoinChan.setText(_translate("MainWindow", "Join / Create chan"))
        self.actionNetworkSwitch.setText(_translate("MainWindow", "Go online/offline"))
        self.actionSupport.setText(_translate("MainWindow", "Support"))
